### ISSUE TITLE
Question Stuck After "Try Again"

### ISSUE THREAD

**Issue by kkhenkina-EXL** [exlskills/exlskills#23] opened 2018-08-13 02:22 UTC
**URL:** https://exlskills.com/learn-en/courses/introduction-to-java-intro_to_java

**Current behavior:** Check answer button locks up if accidentally clicked  

**How to Recreate:** Do not select an answer and click the "Check answer" button.

**What to Fix:** Availability of the button once an answer is selected.

**Expected Outcome:** If the button is clicked without an answer selected, once the answer gets chosen the button should become available again.

**Current State Screenshot:** ![image](https://user-images.githubusercontent.com/33239272/43967087-97581416-9c91-11e8-8a49-5d35c8e96f80.png)

**Comment by svarlamov** [comment] 2018-08-13 04:15
Dupe of #8

**Closed as completed by svarlamov** 2018-08-13 04:15 UTC
